### ISSUE TITLE
Policy "CMP0054" is not known to this version of CMake.

### ISSUE THREAD

**Issue by Kaixhin** [NervanaSystems/cuda-convnet2#2]
This error occurs when running a build on Ubuntu 14.04, which has the latest version of cmake set at 2.8, whilst Policy CMP0054 was introduced in 3.1. Is it possible to check the cmake version and change the build steps appropriately?

**Comment by apark263** [comment]
Thanks for the check -- latest commit should fix it.  Tested internally and works, so closing this for now but please reopen if it is still broken for your env
