### ISSUE TITLE
can't run example using cudanet

### ISSUE THREAD

**Issue by ipanchenko** [NervanaSystems/cuda-convnet2#4]
I try to run the example from neon page using cudanet:
**neon --gpu cudanet examples/convnet/i1k-alexnet-fp32.yaml**
I have no problems with cuda in other frameworks (e.g., Torch) but here I get a following error :

**WARNING:neon.util.persist:deserializing object from:  examples/convnet/i1k-alexnet-fp32.yaml
WARNING:neon.datasets.imageset:Imageset initialized with dtype <type 'numpy.float32'>
2015-08-17 13:42:37,419 WARNING:neon - setting log level to: 20
Traceback (most recent call last):
  File "/opt/anaconda/bin/neon", line 235, in <module>
    experiment, result, status = main()
  File "/opt/anaconda/bin/neon", line 197, in main
    device_id=args.device_id)
  File "/opt/anaconda/lib/python2.7/site-packages/neon/backends/**init**.py", line 99, in gen_backend
    raise RuntimeError("cudanet not found, can't run via GPU")
RuntimeError: cudanet not found, can't run via GPU**

Could you be so kind to help me using your framework?

**Comment by scttl** [comment]
Did you see any warnings/issues when cc2 was installed?  Did you build it as part of neon, or separately?  

One thing that may confirm whether the install was correct, or at least provide more info would be to run:

```
python
import cudanet
```

you need to make sure this works before you'll be able to run neon with this backend.

**Comment by ipanchenko** [comment]
I used cuda-convnet2 from this repo: https://github.com/NervanaSystems/cuda-convnet2
I had no errors on building.
Import does not work in if I use "python"
**import cudanet**
_ImportError: No module named cudanet_

I tried to clarify the reason and I found out that importing is OK, if I use "python3" (my default python is 2.7 as I use Anaconda).

So, what about using neon with cudanet and python 2.7? Is it possible?

**Comment by scttl** [comment]
Yes python2.7 is definitely possible. It sounds like the cudanet backend was installed under python3 though if the import works there. 

If you run: python --version 
What does that show?  Also does it point to your anaconda Python?

**Comment by ipanchenko** [comment]
Sorry for giving you not enough information before. I have checked python version is 2.7.10. and it point to my anaconda install. Moreover, my $PYTHONPATH variable is empty. So it seemed to me like a problem on your side.

**Comment by scttl** [comment]
Just so I'm clear, typing the following does not work:

```
python
import cudanet
```

but the following does:

```
python3
import cudanet
```

If this is correct, could you print the output from each of the following sequences of commands:

1.

```
which python
```

2.

```
/usr/bin/env python --version
```

3.

```
python3
import cudanet
cudanet.__file__
```

**Comment by ipanchenko** [comment]
Actually,  import does not work in python3 as well. 
Previously, I have run this commands in cuda-convnet2 build folder. And it seems like python3 can import a folder not the module (but not python2).

So, the output you asked is:
1. **which python**: _/opt/anaconda/bin/python_
2. **/usr/bin/env python --version**: _/Python 2.7.10 :: Anaconda 2.1.0 (64-bit)_
3. **python3
import cudanet
cudanet.**file****: 
_Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '**file**'_
4. If I run **python3** and **import cudanet** in the folder which does not contain **cudanet** subfolder it outputs same as **python2**: _ImportError: No module named 'cudanet'_

**Comment by scttl** [comment]
Ok, that seems more realistic, so you must have had problems building cuda convnet2.  In that case, first make sure you have all the dependencies listed here: https://code.google.com/p/cuda-convnet2/wiki/Compiling

Then try following the cmake based compilation instructions described in README.md and let us know the output from the `cmake` and `make install` calls (the latter may require `sudo` on Linux).

**Comment by ipanchenko** [comment]
It seems I have all the dependencies and I found nothing special in outputs listed below. 
Here is a cmake output:
**cmake ..**
_-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found CUDA: /usr/local/cuda (found version "7.0") 
-- Found PythonInterp: /opt/anaconda/bin/python (found version "2.7.10") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.6", minimum required is "2.7") 
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- Checking for [mkl - guide - pthread]
-- Checking for [mkl - guide - pthread] -- includes not found
-- Checking for [mkl_ia32 - guide - pthread]
-- Checking for [mkl_ia32 - guide - pthread] -- includes not found
-- Checking for [mkl_em64t - guide - pthread]
-- Checking for [mkl_em64t - guide - pthread] -- includes not found
-- Checking for [cblas - f77blas - atlas]
-- Checking for [cblas - f77blas - atlas] -- includes found
-- Looking for cblas_dgemm
-- Looking for cblas_dgemm - found
-- Checking for [cblas - f77blas - atlas] -- libraries found
-- CBLAS library found
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/cuda-convnet2/build_

And **sudo make install**
_Scanning dependencies of target cconv2_utilpy
[  3%] Building CXX object util/CMakeFiles/cconv2_utilpy.dir/src/matrix.cpp.o
Linking CXX shared library libcconv2_utilpy.so
[  3%] Built target cconv2_utilpy
[  7%] Building NVCC (Device) object nvmatrix/CMakeFiles/cconv2_nvmatrix.dir/src/./cconv2_nvmatrix_generated_nvmatrix_kernels.cu.o
[ 11%] Building NVCC (Device) object nvmatrix/CMakeFiles/cconv2_nvmatrix.dir/src/./cconv2_nvmatrix_generated_memory.cu.o
[ 14%] Building NVCC (Device) object nvmatrix/CMakeFiles/cconv2_nvmatrix.dir/src/./cconv2_nvmatrix_generated_nvmatrix.cu.o
Scanning dependencies of target cconv2_nvmatrix
Linking CXX shared library libcconv2_nvmatrix.so
[ 14%] Built target cconv2_nvmatrix
[ 18%] Building NVCC (Device) object cudaconv3/CMakeFiles/cconv2_cudaconv.dir/src/./cconv2_cudaconv_generated_weight_acts.cu.o
[ 22%] Building NVCC (Device) object cudaconv3/CMakeFiles/cconv2_cudaconv.dir/src/./cconv2_cudaconv_generated_conv_util.cu.o
[ 25%] Building NVCC (Device) object cudaconv3/CMakeFiles/cconv2_cudaconv.dir/src/./cconv2_cudaconv_generated_filter_acts.cu.o
[ 29%] Building NVCC (Device) object cudaconv3/CMakeFiles/cconv2_cudaconv.dir/src/./cconv2_cudaconv_generated_img_acts.cu.o
Scanning dependencies of target cconv2_cudaconv
Linking CXX shared library libcconv2_cudaconv.so
[ 29%] Built target cconv2_cudaconv
[ 33%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_util.cu.o
[ 37%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_actbroadcaster.cu.o
[ 40%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_data.cu.o
[ 44%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_layer_kernels.cu.o
[ 48%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_pyconvnet.cu.o
[ 51%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_weights.cu.o
[ 55%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_convnet.cu.o
[ 59%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_gradreducer.cu.o
[ 62%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_lr.cu.o
[ 66%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_reducepipeline.cu.o
[ 70%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_worker.cu.o
[ 74%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_copypipeline.cu.o
[ 77%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_memorysource.cu.o
[ 81%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_streambroadcast.cu.o
[ 85%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_cost.cu.o
[ 88%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_layer.cu.o
[ 92%] Building NVCC (Device) object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/./cconv2_ConvNet_generated_neuron.cu.o
Scanning dependencies of target cconv2_ConvNet
[ 96%] Building CXX object cudaconvnet/CMakeFiles/cconv2_ConvNet.dir/src/jpeg.cpp.o
Linking CXX shared library libcconv2_ConvNet.so
[ 96%] Built target cconv2_ConvNet
[100%] Building NVCC (Device) object cudanet/CMakeFiles/cconv2_cudanet.dir/src/./cconv2_cudanet_generated_cudanetmat.cu.o
Scanning dependencies of target cconv2_cudanet
Linking CXX shared library libcconv2_cudanet.so
[100%] Built target cconv2_cudanet
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libcconv2_utilpy.so
-- Installing: /usr/local/lib/libcconv2_nvmatrix.so
-- Removed runtime path from "/usr/local/lib/libcconv2_nvmatrix.so"
-- Installing: /usr/local/lib/libcconv2_cudaconv.so
-- Removed runtime path from "/usr/local/lib/libcconv2_cudaconv.so"
-- Installing: /usr/local/lib/libcconv2_ConvNet.so
-- Removed runtime path from "/usr/local/lib/libcconv2_ConvNet.so"
-- Installing: /usr/local/lib/libcconv2_cudanet.so
-- Removed runtime path from "/usr/local/lib/libcconv2_cudanet.so"_

**Comment by scttl** [comment]
Ahh, so it's been a while since I've looked at the CC2 code, and the installation instructions in the README.md only cover the construction of the shared object libraries (that you successfully built into `/usr/local/lib`).  To get the python stuff in, you actually need to run one of the following:

If you have `pip` available in your anaconda distribution (may require a `conda install pip` first), you should be able to just go to the top-level checked out directory and issue:

```
sudo pip install .
```

Alternatively, the following should work too:

```
sudo python setup.py install
```

Sorry for not catching that earlier!  Give one of the above a go and let me know how you get on.

**Comment by ipanchenko** [comment]
Thank you! It seems to work now! But I had to downgrade neon to 0.8.2.
